name: Deploy ClickOnce App to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ./   # Root folder where firebase.json is
