name: Deploy ClickOnce Files to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy static files to Firebase
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ./LfsPublish
