name: Deploy ClickOnce App from Subfolder to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy from subfolder
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ./LfsPublish
    
