name: Deploy ClickOnce Files to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual rerun button

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
